### ISSUE TITLE
Support for complex types

### ISSUE THREAD

**Issue by akzhan** [nodeca/babelfish#13]
Many internationalization engines like Rails i18n support complex value types.

We need to support something like `t('en_US', 'date.abbr_day_names')` with:

``` yaml
date:
  abbr_day_names:
  - Sun
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
```

But when we try to compile it using Babelfish errors thrown.
