### ISSUE TITLE
Support for pluralization-based keys

### ISSUE THREAD

**Issue by akzhan** [nodeca/babelfish#17]
Take a look at this dictionary entries:

``` yaml
datetime:
  distance_in_words:
    less_than_x_minutes:
      one: "less than a minute"
      other: "less than #{count} minutes"
```

Rails pluralization backend supports selection of key based on `count` value.

In addition to typical one, few, manu and other suffixes it supports optional zero suffix.

This cannot be repeated by Babelfish syntax because here a case when no value should be printed.
